# Site settings
name: icodeworld编程世界双师课堂
email: hugo@icodeworld.cn
author: icodeworld
url: https://www.icodeworld.cn
resume_site: https://www.icodeworld.cn
github: https://github.com/icodeworld-double-teacher-classroom
baseurl: ""
description: 万物皆可编程，用创意丰富这个世界吧！
meta_description: icodeworld;icodeworld编程世界双师课堂;icodeworld编程世界;少儿编程课程授权;少儿编程;编程世界
motto: 万物皆可编程，用创意丰富这个世界吧！
banner: 完全开放的世界，学中玩，玩中学

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: icodeworld-double-teacher-classroom

# Build settings
markdown: kramdown

baidu_analysis: 
